# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

ARG BASE_VERSION=15
ARG ORGANIZR_VERSION=2.1
FROM ghcr.io/daemonless/nginx-base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG ORGANIZR_VERSION
ARG PACKAGES="git-lite php84 php84-curl php84-pdo_sqlite php84-sqlite3 php84-session php84-simplexml php84-xml php84-xmlwriter php84-zip php84-zlib php84-fileinfo php84-filter php84-ldap php84-ctype php84-iconv php84-mbstring"
ARG UPSTREAM_URL="https://api.github.com/repos/causefx/Organizr/releases/latest"
ARG UPSTREAM_JQ=".tag_name"
ARG HEALTHCHECK_ENDPOINT="http://localhost:8083/daemonless-ping"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"

# --- Metadata (Injected by Generator) ---
LABEL org.opencontainers.image.title="Organizr" \
      org.opencontainers.image.description="HTPC/Homelab Services Organizer on FreeBSD." \
      org.opencontainers.image.source="https://github.com/daemonless/organizr" \
      org.opencontainers.image.url="https://organizr.app/" \
      org.opencontainers.image.documentation="https://docs.organizr.app/" \
      org.opencontainers.image.version="${ORGANIZR_VERSION}" \
      org.opencontainers.image.licenses="GPL-3.0-only" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Utilities" \
      io.daemonless.port="8083" \
      io.daemonless.volumes="/config" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.base="nginx" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.upstream-jq="${UPSTREAM_JQ}" \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}" \
      io.daemonless.packages="${PACKAGES}"

# Install PHP, git, and required extensions
# Note: openssl is built into base php84 package
# Note: umask 022 ensures directories are created with correct permissions
RUN umask 022 && pkg update && \
    pkg install -y \
    ${PACKAGES} && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/* && \
    mkdir -p /app && \
    echo "${ORGANIZR_VERSION}" > /app/version

# Pre-clone Organizr at build time (runtime can update if network available)
ARG BRANCH=v2-master
RUN git clone -b "${BRANCH}" --depth 1 https://github.com/causefx/Organizr /app/organizr && \
    rm -rf /app/organizr/.git

# Copy default configs and scripts
COPY root/ /

# Make scripts executable and set up php-fpm service
RUN chmod +x /etc/cont-init.d/* /etc/services.d/*/run 2>/dev/null || true

# --- Expose (Injected by Generator) ---
EXPOSE 8083

# --- Volumes (Injected by Generator) ---
VOLUME /config